# _config.yml

# required, replace with your own information -----
title: Comunidad de Live Coders - Perú
author: Sensáfona
description: > 
  Grupo abierto para aprender y compartir. Música, visuales, tecnología. Esperamos ser un nodo internacional de TOPLAP y organizar eventos descentralizados a partir de convocatorias abiertas.
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

